#ifndef MICROPY_INCLUDED_GENHDR_MPVERSION_H
#define MICROPY_INCLUDED_GENHDR_MPVERSION_H
#define MICROPY_VERSION_MAJOR 1
#define MICROPY_VERSION_MINOR 20
#define MICROPY_VERSION_MICRO 0
#define MICROPY_GIT_TAG "v1.0.0-pykernel-gui"
#define MICROPY_GIT_HASH "custom"
#define MICROPY_BUILD_DATE "2026-09-24"
#define MICROPY_SYS_VERSION_INFO "1.20.0"
#define MICROPY_HW_BOARD_NAME "PyKernel Baremetal"
#define MICROPY_HW_MCU_NAME   "i686 Protected Mode"
#endif