// Auto-generated by gen_root_pointers.py

MP_REGISTER_ROOT_POINTER(mp_obj_base_t * cur_exception);
MP_REGISTER_ROOT_POINTER(mp_obj_list_t mp_sys_argv_obj);
MP_REGISTER_ROOT_POINTER(mp_obj_list_t mp_sys_path_obj);
MP_REGISTER_ROOT_POINTER(mp_obj_t sys_exitfunc);
MP_REGISTER_ROOT_POINTER(mp_obj_t sys_mutable[MP_SYS_MUTABLE_NUM]);
MP_REGISTER_ROOT_POINTER(mp_obj_t track_reloc_code_list);
MP_REGISTER_ROOT_POINTER(mp_sched_item_t sched_queue[MICROPY_SCHEDULER_DEPTH]);
