import os, re

ROOT = os.path.dirname(os.path.abspath(__file__))
OUT  = os.path.join(ROOT, "genhdr", "root_pointers.h")
SCAN_DIRS = [os.path.join(ROOT, "py"), os.path.join(ROOT, "extmod")]

pat = re.compile(r'^\s*MP_REGISTER_ROOT_POINTER\s*\(\s*(.+?)\s*\)\s*;?\s*$')

found = set()
for d in SCAN_DIRS:
    if not os.path.isdir(d):
        continue
    for dirpath, _, files in os.walk(d):
        for fn in files:
            if not fn.endswith(".c"):
                continue
            path = os.path.join(dirpath, fn)
            try:
                with open(path, "r", encoding="utf-8", errors="ignore") as f:
                    for line in f:
                        if line.lstrip().startswith("#"):
                            continue
                        m = pat.match(line)
                        if not m:
                            continue
                        arg = m.group(1).strip()
                        if not arg or "variable_declaration" in arg:
                            continue
                        found.add(arg)
            except OSError:
                pass

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8") as f:
    f.write("// Auto-generated by gen_root_pointers.py\n\n")
    for arg in sorted(found):
        f.write("MP_REGISTER_ROOT_POINTER({});\n".format(arg))

print("Da sinh {} root pointer vao {}".format(len(found), OUT))